# Generated by Django 5.0 on 2024-02-27 17:11

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_rate', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EmailNotificationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_email', models.CharField(blank=True, max_length=50)),
                ('notification_message', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='VendorBusinessDetails',
            fields=[
                ('vendor_email', models.CharField(blank=True, max_length=50)),
                ('vendor_BusinessName', models.CharField(blank=True, max_length=50)),
                ('vendor_phoneNumber', models.CharField(blank=True, max_length=50)),
                ('vendor_Location', models.CharField(blank=True, max_length=50)),
                ('vendor_id', models.IntegerField(default='0000', primary_key=True, serialize=False)),
                ('vendor_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('vendor_about', models.TextField(blank=True)),
                ('vendor_opening_days', models.CharField(blank=True, max_length=12)),
                ('vendor_opening_time', models.CharField(blank=True, max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='VendorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_email', models.CharField(blank=True, max_length=50)),
                ('vendor_BusinessName', models.CharField(blank=True, max_length=50)),
                ('vendor_phoneNumber', models.CharField(blank=True, max_length=50)),
                ('vendor_Location', models.CharField(blank=True, max_length=50)),
                ('vendor_about', models.TextField(blank=True)),
                ('vendor_opening_days', models.CharField(blank=True, max_length=12)),
                ('vendor_opening_time', models.CharField(blank=True, max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.IntegerField(choices=[(1, 'Customer'), (2, 'Vendor')], default=1)),
                ('username', models.CharField(max_length=50)),
                ('full_name', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('phonenumber', models.CharField(blank=True, max_length=100)),
                ('vendor_about', models.TextField(blank=True)),
                ('vendor_opening_days', models.CharField(blank=True, max_length=12)),
                ('vendor_opening_time', models.CharField(blank=True, max_length=12)),
                ('groups', models.ManyToManyField(related_name='karkhana_users', to='auth.group')),
                ('user_permissions', models.ManyToManyField(related_name='karkhana_users_permissions', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField(null=True)),
                ('Customer_Name', models.CharField(blank=True, max_length=70)),
                ('Customer_Email', models.CharField(blank=True, max_length=70)),
                ('Feedbacks', models.CharField(blank=True, max_length=500)),
                ('Customer_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewsRatings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Business_Name', models.CharField(blank=True, max_length=70)),
                ('Customer_Name', models.CharField(blank=True, max_length=70)),
                ('Rating', models.FloatField(blank=True, default=0)),
                ('Review', models.CharField(blank=True, max_length=500)),
                ('Business_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karkhana_app.vendorbusinessdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Deals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BusinessName', models.CharField(blank=True, max_length=50)),
                ('Business_ProfileImage', models.ImageField(blank=True, null=True, upload_to='')),
                ('BusinessLocation', models.CharField(blank=True, max_length=50, null=True)),
                ('Business_Phone', models.CharField(blank=True, max_length=50)),
                ('deal_title', models.CharField(max_length=70)),
                ('deal_price', models.IntegerField(blank=True, default=0)),
                ('deal_photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('deal_category', models.CharField(max_length=20)),
                ('deal_desc', models.TextField()),
                ('deal_condition', models.TextField(blank=True)),
                ('deal_discount', models.IntegerField(blank=True, default=0)),
                ('deal_applicable_time', models.CharField(max_length=10)),
                ('deal_applicable_day', models.CharField(max_length=10)),
                ('deal_expiry_date', models.CharField(max_length=12)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karkhana_app.vendorbusinessdetails')),
            ],
        ),
        migrations.CreateModel(
            name='CouponActive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_title', models.CharField(blank=True, max_length=70)),
                ('deal_photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('deal_discount', models.IntegerField(blank=True, default=0)),
                ('deal_applicable_time', models.CharField(blank=True, max_length=10)),
                ('deal_applicable_day', models.CharField(blank=True, max_length=10)),
                ('deal_expiry_date', models.CharField(blank=True, max_length=12)),
                ('VendorBusiness_Name', models.CharField(blank=True, max_length=50)),
                ('VendorBusiness_Location', models.CharField(blank=True, max_length=50)),
                ('Vendor_Phone', models.CharField(blank=True, max_length=50)),
                ('Total_Coupon_Price', models.IntegerField(blank=True, default=0)),
                ('Customer_Name', models.CharField(blank=True, max_length=50)),
                ('Customer_Address', models.CharField(blank=True, max_length=100)),
                ('Customer_Phonenumber', models.CharField(blank=True, max_length=50)),
                ('Customer_Email', models.CharField(blank=True, max_length=50)),
                ('coupon_Status', models.CharField(choices=[('Active', 'ACTIVE'), ('Used', 'USED')], default='Active', max_length=20)),
                ('Customer_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Vendor_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karkhana_app.vendorbusinessdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_title', models.CharField(max_length=70)),
                ('deal_price', models.IntegerField(blank=True, default=0)),
                ('deal_photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('deal_category', models.CharField(max_length=20)),
                ('deal_desc', models.TextField()),
                ('deal_condition', models.TextField(blank=True)),
                ('deal_discount', models.IntegerField(blank=True, default=0)),
                ('deal_applicable_time', models.CharField(max_length=10)),
                ('deal_applicable_day', models.CharField(max_length=10)),
                ('deal_expiry_date', models.CharField(max_length=12)),
                ('VendorBusiness_Name', models.CharField(blank=True, max_length=50)),
                ('VendorBusiness_Location', models.CharField(blank=True, max_length=50)),
                ('VendorBusiness_ProfileImage', models.ImageField(blank=True, null=True, upload_to='')),
                ('Vendor_Phone', models.CharField(blank=True, max_length=50)),
                ('Customer_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Vendor_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karkhana_app.vendorbusinessdetails')),
            ],
        ),
    ]
