# Generated by Django 5.0 on 2024-02-16 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karkhana_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_rate', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EmailNotificationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_email', models.CharField(blank=True, max_length=50)),
                ('notification_message', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_title', models.CharField(max_length=70)),
                ('deal_price', models.IntegerField(blank=True, default=0)),
                ('deal_photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('deal_category', models.CharField(max_length=20)),
                ('deal_desc', models.TextField()),
                ('deal_condition', models.TextField(blank=True)),
                ('deal_discount', models.IntegerField(blank=True, default=0)),
                ('deal_applicable_time', models.CharField(max_length=10)),
                ('deal_applicable_day', models.CharField(max_length=10)),
                ('deal_expiry_date', models.CharField(max_length=12)),
                ('VendorBusiness_Name', models.CharField(blank=True, max_length=50)),
                ('VendorBusiness_Location', models.CharField(blank=True, max_length=50)),
                ('VendorBusiness_ProfileImage', models.ImageField(blank=True, null=True, upload_to='')),
                ('Vendor_Phone', models.CharField(blank=True, max_length=50)),
                ('Customer_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Vendor_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karkhana_app.vendorbusinessdetails')),
            ],
        ),
        migrations.CreateModel(
            name='CouponActive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_title', models.CharField(blank=True, max_length=70)),
                ('deal_photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('deal_discount', models.IntegerField(blank=True, default=0)),
                ('deal_applicable_time', models.CharField(blank=True, max_length=10)),
                ('deal_applicable_day', models.CharField(blank=True, max_length=10)),
                ('deal_expiry_date', models.CharField(blank=True, max_length=12)),
                ('VendorBusiness_Name', models.CharField(blank=True, max_length=50)),
                ('VendorBusiness_Location', models.CharField(blank=True, max_length=50)),
                ('Vendor_Phone', models.CharField(blank=True, max_length=50)),
                ('Total_Coupon_Price', models.IntegerField(blank=True, default=0)),
                ('Customer_Name', models.CharField(blank=True, max_length=50)),
                ('Customer_Address', models.CharField(blank=True, max_length=100)),
                ('Customer_Phonenumber', models.CharField(blank=True, max_length=50)),
                ('Customer_Email', models.CharField(blank=True, max_length=50)),
                ('coupon_Status', models.CharField(choices=[('Active', 'ACTIVE'), ('Used', 'USED')], default='Active', max_length=20)),
                ('Customer_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Vendor_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karkhana_app.vendorbusinessdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Deals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BusinessName', models.CharField(blank=True, max_length=50)),
                ('Business_ProfileImage', models.ImageField(blank=True, null=True, upload_to='')),
                ('BusinessLocation', models.CharField(blank=True, max_length=50, null=True)),
                ('Business_Phone', models.CharField(blank=True, max_length=50)),
                ('deal_title', models.CharField(max_length=70)),
                ('deal_price', models.IntegerField(blank=True, default=0)),
                ('deal_photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('deal_category', models.CharField(max_length=20)),
                ('deal_desc', models.TextField()),
                ('deal_condition', models.TextField(blank=True)),
                ('deal_discount', models.IntegerField(blank=True, default=0)),
                ('deal_applicable_time', models.CharField(max_length=10)),
                ('deal_applicable_day', models.CharField(max_length=10)),
                ('deal_expiry_date', models.CharField(max_length=12)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karkhana_app.vendorbusinessdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField(null=True)),
                ('Customer_Name', models.CharField(blank=True, max_length=70)),
                ('Customer_Email', models.CharField(blank=True, max_length=70)),
                ('Feedbacks', models.CharField(blank=True, max_length=500)),
                ('Customer_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewsRatings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Business_Name', models.CharField(blank=True, max_length=70)),
                ('Customer_Name', models.CharField(blank=True, max_length=70)),
                ('Rating', models.FloatField(blank=True, default=0)),
                ('Review', models.CharField(blank=True, max_length=500)),
                ('Business_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karkhana_app.vendorbusinessdetails')),
            ],
        ),
    ]
